### ISSUE TITLE
low train accuracy (10% / 40%) on synthetic language modeling tasks for H3

### ISSUE THREAD

**Issue by YilunKuang** [HazyResearch/safari#35]
I was reproducing these two runs 

```
python -m train experiment=synthetics/associative_recall/h3
python -m train experiment=synthetics/induction_head/h3
```

from https://github.com/HazyResearch/safari/blob/main/experiments.md and got the following results respectively: 

```
# associative recall
Epoch 399: 100%|██████████| 189/189 [00:02<00:00, 66.60it/s, loss=1.47, val/accuracy_ignore_index=0.980, val/loss=0.0471, val/perplexity=1.050, test/accuracy_ignore_index=0.980, test/loss=0.0471, test/perplexity=1.050, train/accuracy_ignore_index=0.410, train/loss=1.470, train/perplexity=4.370]
```

```
# induction head
Epoch 399: 100%|██████████| 189/189 [00:02<00:00, 65.47it/s, loss=2.63, val/accuracy_ignore_index=1.000, val/loss=0.0804, val/perplexity=1.080, test/accuracy_ignore_index=1.000, test/loss=0.0804, test/perplexity=1.080, train/accuracy_ignore_index=0.165, train/loss=2.640, train/perplexity=14.00]
```

For both tasks, test accuracies are above 97% as expected, but train accuracies are around `train/accuracy_ignore_index=0.410` and `train/accuracy_ignore_index=0.165`. Any reason why this might happen?

**Comment by DanFu09** [comment]
This is expected - train loss is evaluated on all tokens (a la masked
language modeling), and test is only evaluated on the last token.

During training, it’s impossible to know the answer to half the tokens ,
since it’s the first time seeing a particular key/value pair - hence the
low values. High scores during training are actually indicative that a
model is “cheating” and is non-causal.

**Comment by YilunKuang** [comment]
OK, thanks for the clarification! Feel free to close this issue.
